### ISSUE TITLE
Forecast API not working

### ISSUE THREAD

**Issue by Schmiddi1008** [chpro/fronius-grafana-dashboard#5]
Hi, 
the Forecast API isnt working.

In influxdb i cant see the measurement. 

My telegraf.conf:

![image](https://github.com/chpro/fronius-grafana-dashboard/assets/155877587/7baf9143-fad9-4c7e-8b5f-6f84e092504a)

Photovoltaik: East/West

**Comment by chpro** [comment]
can you also give me info how you configured the [[outputs.influxdb_v2]] and [agent]

**Comment by Schmiddi1008** [comment]
![image](https://github.com/chpro/fronius-grafana-dashboard/assets/155877587/56a158a0-d7ea-4ad0-9376-71a796f3de69)

**Comment by chpro** [comment]
It seems that everything is configured the right way.

Is there some error in the log /var/log/telegraf/telegraf.log?

Can you also check if the data is maybe written to another bucket e.g. the bucket `inverter` which is the default one. This could happen if the override of bucket name does not work.

**Comment by Schmiddi1008** [comment]
![image](https://github.com/chpro/fronius-grafana-dashboard/assets/155877587/56ccb1cf-9b1d-4506-a9d1-23599211df69)

**Comment by chpro** [comment]
I had a closer look at the config and log. Found nothing obvious why it should not work, sorry.

May be it helps to find the problem when I describe the workflow to you:
- inputs.http reads the desired forecast every 8h. The large interval was necessary because of rate limit of the free tier.
- no processors should be applied before sending data to output
- in the outputs.influxdb_v2 writes the data to influx by default to the `inverter` bucket this is overwritten by the tag `influxdb_bucket` in the case of the forecast the bucket `pvforecast` is used.

What I would do next:
- check for any typos of bucket names in influx and telegraph
- turn on debug logging in telegraf to see what's happening. For that you can use following config for [agent]
```
   ## Log at debug level.
  debug = true
  ## Log only error level messages.
  quiet = false
```
Be aware of the high interval this may need to be changed. I would also recommend to only have the forecast inputs.http enabled while debugging.

If you got some more insights or solution don't hesitate to contact me.

**Comment by Schmiddi1008** [comment]
Hi, 
dont know why, but its working. Ive changed the token.... 

Do you know how i can create a link for East / West ? Or is it possible to use 2 links ? One for east and one for west

**Comment by chpro** [comment]
You can use two urls in the `inputs.http` block with comma separation

```
  urls = [
    "https://api.forecast.solar/estimate/watthours/day/46.0/15.0/45/0/10.2?time=utc",
    "https://api.forecast.solar/estimate/watthours/day/46.0/15.0/45/90/10.2?time=utc"
  ]
```

Then you will end up with also additional measures for each day in INFLUXDB. It is possible to distinguish the East / West measure by `url` field.

<img width="369" alt="Screenshot 2024-01-15 at 06 46 53" src="https://github.com/chpro/fronius-grafana-dashboard/assets/5706722/b7d23112-7403-4a27-a376-fb2b81c868b9">

Hence, you have also adapt the panel current queries and add additional queries. To current queries you have to add a  restriction `url = 'YOUR_FORECAST_URL'` in where clause.

e.g.

```
SELECT first("value") FROM "autogen"."pv_forecast_watt_hours_day" WHERE $timeFilter and url = 'https://api.forecast.solar/estimate/watthours/day/46.0/15.0/45/0/10.2?time=utc' tz('${tz:raw}')
```

The panel would look like 
<img width="317" alt="Screenshot 2024-01-15 at 06 53 23" src="https://github.com/chpro/fronius-grafana-dashboard/assets/5706722/91c6f291-2774-486d-904f-a6cf30b5511d">
when you change queries as follows
<img width="1282" alt="Screenshot 2024-01-15 at 06 55 37" src="https://github.com/chpro/fronius-grafana-dashboard/assets/5706722/59681be4-d262-4d33-9f6e-caa8350afbd4">
