### ISSUE TITLE
Database not found Error

### ISSUE THREAD

**Issue by Peddaahh** [chpro/fronius-grafana-dashboard#7]
I've setup everything according to the readme.. however it is not working for me
![image](https://github.com/chpro/fronius-grafana-dashboard/assets/37550489/2e60b327-b9ef-4b65-ba31-0355da3b0727)
![image](https://github.com/chpro/fronius-grafana-dashboard/assets/37550489/af287960-3120-41bf-a08b-6a4da1de6a72)
![image](https://github.com/chpro/fronius-grafana-dashboard/assets/37550489/bd76c516-112b-488a-a055-073913dfafa2)

**Comment by Peddaahh** [comment]
So token should be fine
![Screenshot_20240305_174046_Brave](https://github.com/chpro/fronius-grafana-dashboard/assets/37550489/fe9619b5-047c-4ff7-9d07-7654e4b7536b)
![Screenshot_20240305_174021_Brave](https://github.com/chpro/fronius-grafana-dashboard/assets/37550489/ece74e6d-0051-45c0-a920-1a4ca6703bba)

**Comment by Peddaahh** [comment]
Just for clarification: Is there a difference between database and bucket?

**Comment by chpro** [comment]
It seems there is a difference between database and bucket. Here you can find a description about it https://ivanahuckova.medium.com/setting-up-influxdb-v2-flux-with-influxql-in-grafana-926599a19eeb please try to follow the instructions about Map InfluxDB v2 buckets to InfluxDB v1 databases. If it works I will add it to the README

I did not have the problem because I have migrated from InfluxDB v1 to InfluxDB v2.

**Comment by Peddaahh** [comment]
Yes it works, should be added to README. Buckets aren't DBs in V2. So I assume they are migrated when upgrading from V1. It is important that the rentention policy name (rp) is autogen! With `influx bucket list` you can retrieve the IDs needed for the following command.
```influx v1 dbrp update \
  --id 00oxo0X0xx0XXoX0 \
  --rp autogen \
  --default\
  -o organisation \
  -t abcTOKENxyz```
