### ISSUE TITLE
Integration with Powerwall Dashboard

### ISSUE THREAD

**Issue by aesculus** [chpro/fronius-grafana-dashboard#9]
In the credits you state that this work is based on Powerwall Dashboard. Do you have a setup that describes how you would integrate this feed/dashboard into Powerwall Dashboard?

It looks like some of your telegraph.conf would be copied into the Powerwall Dashboard telegraph.conf and some of your dashboard elements could be copied into the PW DB too.

Also when using multiple inverters is this correct?

  ## One or more URLs from which to read formatted metrics
  urls = [
    "http://inverter/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=0&DataCollection=CommonInverterData",
    "http://inverter/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=0&DataCollection=3PInverterData",
    "http://inverter/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData",
    "http://inverter/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=3PInverterData"

  ]

**Comment by chpro** [comment]
Hello,

to your first question about integration of Powerwall Dashboard at the end all the queries were rewritten because also the data structure is different. You can copy the panels to any other dashboard which has the variable `tz` set properly.

The second question about multiple inverters. The approach with different urls is feasable but you need to think about how to integrate this into the existing panel because currently multiple inverters are not supported. You can either repeat each panel or row for each inverter or sum up the values. For both options you need to do adaptations.

**Comment by aesculus** [comment]
Thank you for the response.
